apiVersion: core.jenkins-x.io/v4beta1
kind: Requirements
spec:
  autoUpdate:
    enabled: false
    schedule: ""
  cluster:
    chartKind: pages
    chartRepository: http://k3d-tekton-server-0:8200
    clusterName: kind
    devEnvApprovers:
    - todo
    environmentGitOwner: todo
    gitKind: github
    gitName: github
    gitServer: https://github.com
    provider: kubernetes
    registry: ghcr.io
  environments:
  - key: dev
    owner: fsedano
    repository: myvault-jx
  - key: staging
  ingress:
    domain: ""
    ignoreLoadBalancer: true
    kind: ingress
    namespaceSubDomain: .jx.
    tls:
      email: ""
      enabled: false
      production: false
  pipelineUser:
    username: fsedano
  repository: bucketrepo
  secretStorage: vault
  vault:
    url: 127.0.0.1:8200
  webhook: lighthouse
